import { Role, User } from './user.model';

export const USERS: User[] = [
  {
    uid: 'skjpmgt876',
    email: 'skjpmgt876@example.com',
    photoURL: 'https://picsum.photos/500?random=22',
    displayName: 'User skjpmgt876',
    role: Role.EDITOR,
  },
  {
    uid: 'kuda842fg8a',
    email: 'kuda842fg8a@example.com',
    photoURL: 'https://picsum.photos/500?random=47',
    displayName: 'User kuda842fg8a',
    role: Role.EDITOR,
  },
  {
    uid: 's5j1flxlg6',
    email: 's5j1flxlg6@example.com',
    photoURL: 'https://picsum.photos/500?random=62',
    displayName: 'User s5j1flxlg6',
    role: Role.EDITOR,
  },
  {
    uid: 'coa4qb0nra9',
    email: 'coa4qb0nra9@example.com',
    photoURL: 'https://picsum.photos/500?random=85',
    displayName: 'User coa4qb0nra9',
    role: Role.EDITOR,
  },
  {
    uid: 'xft6akox6yk',
    email: 'xft6akox6yk@example.com',
    photoURL: 'https://picsum.photos/500?random=93',
    displayName: 'User xft6akox6yk',
    role: Role.EDITOR,
  },
  {
    uid: 'ls8rkppqb09',
    email: 'ls8rkppqb09@example.com',
    photoURL: 'https://picsum.photos/500?random=95',
    displayName: 'User ls8rkppqb09',
    role: Role.EDITOR,
  },
  {
    uid: 'jeok53c6umh',
    email: 'jeok53c6umh@example.com',
    photoURL: 'https://picsum.photos/500?random=97',
    displayName: 'User jeok53c6umh',
    role: Role.EDITOR,
  },
  {
    uid: 'q2ry22od94',
    email: 'q2ry22od94@example.com',
    photoURL: 'https://picsum.photos/500?random=4',
    displayName: 'User q2ry22od94',
    role: Role.ADMIN,
  },
  {
    uid: 'aybaws8ck2b',
    email: 'aybaws8ck2b@example.com',
    photoURL: 'https://picsum.photos/500?random=21',
    displayName: 'User aybaws8ck2b',
    role: Role.EDITOR,
  },
  {
    uid: 'm3mmawikgwc',
    email: 'm3mmawikgwc@example.com',
    photoURL: 'https://picsum.photos/500?random=99',
    displayName: 'User m3mmawikgwc',
    role: Role.ADMIN,
  },
  {
    uid: '4eg02gdcojm',
    email: '4eg02gdcojm@example.com',
    photoURL: 'https://picsum.photos/500?random=70',
    displayName: 'User 4eg02gdcojm',
    role: Role.EDITOR,
  },
  {
    uid: 'juicp5aqdj',
    email: 'juicp5aqdj@example.com',
    photoURL: 'https://picsum.photos/500?random=40',
    displayName: 'User juicp5aqdj',
    role: Role.EDITOR,
  },
  {
    uid: 'dbjw058omx6',
    email: 'dbjw058omx6@example.com',
    photoURL: 'https://picsum.photos/500?random=71',
    displayName: 'User dbjw058omx6',
    role: Role.EDITOR,
  },
  {
    uid: 'gh7a860qnx',
    email: 'gh7a860qnx@example.com',
    photoURL: 'https://picsum.photos/500?random=74',
    displayName: 'User gh7a860qnx',
    role: Role.ADMIN,
  },
  {
    uid: 'xgoppt0up7r',
    email: 'xgoppt0up7r@example.com',
    photoURL: 'https://picsum.photos/500?random=84',
    displayName: 'User xgoppt0up7r',
    role: Role.EDITOR,
  },
  {
    uid: '4o5pe2gobo7',
    email: '4o5pe2gobo7@example.com',
    photoURL: 'https://picsum.photos/500?random=57',
    displayName: 'User 4o5pe2gobo7',
    role: Role.EDITOR,
  },
  {
    uid: 'o2qct6r0yya',
    email: 'o2qct6r0yya@example.com',
    photoURL: 'https://picsum.photos/500?random=39',
    displayName: 'User o2qct6r0yya',
    role: Role.EDITOR,
  },
  {
    uid: 'oel4sffr2p',
    email: 'oel4sffr2p@example.com',
    photoURL: 'https://picsum.photos/500?random=23',
    displayName: 'User oel4sffr2p',
    role: Role.EDITOR,
  },
  {
    uid: 'bqjqqlzszau',
    email: 'bqjqqlzszau@example.com',
    photoURL: 'https://picsum.photos/500?random=19',
    displayName: 'User bqjqqlzszau',
    role: Role.ADMIN,
  },
  {
    uid: 'lpzbvqwqfze',
    email: 'lpzbvqwqfze@example.com',
    photoURL: 'https://picsum.photos/500?random=92',
    displayName: 'User lpzbvqwqfze',
    role: Role.EDITOR,
  },
];
